version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dep"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "📌"
    labels:
      - "dependencies"